// <auto-generated />
using System;
<<<<<<<< HEAD:FoodControl/Migrations/20231102164319_first migration.Designer.cs
========
using FoodControl.Models;
>>>>>>>> 9c783497dcf175db3ccf5f17b316c768d9d285b7:FoodControl/Migrations/20231102015753_firstmig.Designer.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLiteTeste.Models;

#nullable disable

namespace FoodControl.Migrations
{
<<<<<<<< HEAD:FoodControl/Migrations/20231102164319_first migration.Designer.cs
    [DbContext(typeof(DogTreatmentDbContext))]
    [Migration("20231102164319_first migration")]
    partial class firstmigration
========
    [DbContext(typeof(DogtreatmentsContext))]
    [Migration("20231102015753_firstmig")]
    partial class firstmig
>>>>>>>> 9c783497dcf175db3ccf5f17b316c768d9d285b7:FoodControl/Migrations/20231102015753_firstmig.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("FoodControl.Models.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Food")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingFood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingWater")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Water")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("tbDogTreatments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
