// <auto-generated />
using System;
<<<<<<<< HEAD:FoodControl/Migrations/DogTreatmentDbContextModelSnapshot.cs
========
using FoodControl.Models;
>>>>>>>> 9c783497dcf175db3ccf5f17b316c768d9d285b7:FoodControl/Migrations/DogtreatmentsContextModelSnapshot.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLiteTeste.Models;

#nullable disable

namespace FoodControl.Migrations
{
<<<<<<<< HEAD:FoodControl/Migrations/DogTreatmentDbContextModelSnapshot.cs
    [DbContext(typeof(DogTreatmentDbContext))]
    partial class DogTreatmentDbContextModelSnapshot : ModelSnapshot
========
    [DbContext(typeof(DogtreatmentsContext))]
    partial class DogtreatmentsContextModelSnapshot : ModelSnapshot
>>>>>>>> 9c783497dcf175db3ccf5f17b316c768d9d285b7:FoodControl/Migrations/DogtreatmentsContextModelSnapshot.cs
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("FoodControl.Models.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Food")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingFood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingWater")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Water")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("tbDogTreatments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
